# Generated by Django 3.2.9 on 2021-11-18 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFieldAdvantage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperBowlHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100)),
                ('winProb', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='SuperBowlTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName1', models.CharField(max_length=100)),
                ('teamName2', models.CharField(max_length=100)),
                ('teamScore1', models.IntegerField(default=0)),
                ('teamScore2', models.IntegerField(default=0)),
                ('winProb1', models.CharField(max_length=100)),
                ('winProb2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TestTbl',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('wins', models.IntegerField()),
                ('last_game_date', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HomeFieldAdvantage.teams')),
            ],
            options={
                'db_table': 'test_tbl',
            },
        ),
    ]
