# Generated by Django 3.2.9 on 2021-11-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFieldAdvantage', '0003_auto_20211117_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boxscore',
        ),
    ]
