# Generated by Django 3.2.9 on 2021-11-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFieldAdvantage', '0005_auto_20211117_2326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boxscore',
        ),

    ]
