# Generated by Django 3.2.9 on 2021-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeFieldAdvantage', '0006_delete_boxscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPullDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pull_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Last_Pull',
            },
        ),
    ]
