team_dict = {
    'Arizona Cardinals': {'abbr': "CRD", 'img': "ARI.png"},
    'Atlanta Falcons': {'abbr': "ATL", 'img': "ATL.png"},
    'Baltimore Ravens': {'abbr': "RAV", 'img': "BAL.png"},
    'Buffalo Bills': {'abbr': "BUF", 'img': "BUF.png"},
    'Carolina Panthers': {'abbr': "CAR", 'img': "CAR.png"},
    'Chicago Bears': {'abbr': "CHI", 'img': "CHI.png"},
    'Cincinnati Bengals': {'abbr': "CIN", 'img': "CIN.png"},
    'Cleveland Browns': {'abbr': "CLE", 'img': "CLE.png"},
    'Dallas Cowboys': {'abbr': "DAL", 'img': "DAL.png"},
    'Denver Broncos': {'abbr': "DEN", 'img': "DEN.png"},
    'Detroit Lions': {'abbr': "DET", 'img': "DET.png"},
    'Green Bay Packers': {'abbr': "GNB", 'img': "GBP.png"},
    'Houston Texans': {'abbr': "HTX", 'img': "HTX.png"},
    'Indianapolis Colts': {'abbr': "CLT", 'img': "IND.png"},
    'Jacksonville Jaguars': {'abbr': "JAX", 'img': "JAX.png"},
    'Kansas City Chiefs': {'abbr': "KAN", 'img': "KAN.png"},
    'Las Vegas Raiders': {'abbr': "RAI", 'img': "VEG.png"},
    'Los Angeles Chargers': {'abbr': "SDG", 'img': "LAC.png"},
    'Los Angeles Rams': {'abbr': "RAM", 'img': "RAM.png"},
    'Miami Dolphins': {'abbr': "MIA", 'img': "MIA.png"},
    'Minnesota Vikings': {'abbr': "MIN", 'img': "MIN.png"},
    'New England Patriots': {'abbr': "NWE", 'img': "NEW.png"},
    'New Orleans Saints': {'abbr': "NOR", 'img': "NOR.png"},
    'New York Giants': {'abbr': "NYG", 'img': "NYG.png"},
    'New York Jets': {'abbr': "NYJ", 'img': "NYJ.png"},
    'Philadelphia Eagles': {'abbr': "PHI", 'img': "PHI.png"},
    'Pittsburgh Steelers': {'abbr': "PIT", 'img': "PIT.png"},
    'San Francisco 49ers': {'abbr': "SFO", 'img': "SFO.png"},
    'Seattle Seahawks': {'abbr': "SEA", 'img': "SEA.png"},
    'Tampa Bay Buccaneers': {'abbr': "TAM", 'img': "TAM.png"},
    'Tennessee Titans': {'abbr': "OTI", 'img': "TEN.png"},
    'Washington Football Team': {'abbr': "WAS", 'img': "WAS.png"},
}